package com.example.demo.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.number
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.readcount
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer readcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private String author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.number
     *
     * @return the value of book.number
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.number
     *
     * @param number the value for book.number
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.readcount
     *
     * @return the value of book.readcount
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getReadcount() {
        return readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.readcount
     *
     * @param readcount the value for book.readcount
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }
}