package com.example.demo.model;

public class People {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.name
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.age
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.locale
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private String locale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.qq
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.email
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.id
     *
     * @return the value of people.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.id
     *
     * @param id the value for people.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.name
     *
     * @return the value of people.name
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.name
     *
     * @param name the value for people.name
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.age
     *
     * @return the value of people.age
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.age
     *
     * @param age the value for people.age
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.locale
     *
     * @return the value of people.locale
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.locale
     *
     * @param locale the value for people.locale
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setLocale(String locale) {
        this.locale = locale == null ? null : locale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.qq
     *
     * @return the value of people.qq
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.qq
     *
     * @param qq the value for people.qq
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.email
     *
     * @return the value of people.email
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.email
     *
     * @param email the value for people.email
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}