package com.example.demo.model;

import java.util.Date;

public class Readrecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrecord.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrecord.user_id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrecord.book_id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrecord.read_time
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    private Date readTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrecord.id
     *
     * @return the value of readrecord.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrecord.id
     *
     * @param id the value for readrecord.id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrecord.user_id
     *
     * @return the value of readrecord.user_id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrecord.user_id
     *
     * @param userId the value for readrecord.user_id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrecord.book_id
     *
     * @return the value of readrecord.book_id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrecord.book_id
     *
     * @param bookId the value for readrecord.book_id
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrecord.read_time
     *
     * @return the value of readrecord.read_time
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrecord.read_time
     *
     * @param readTime the value for readrecord.read_time
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }
}