package com.example.demo.dao;

import com.example.demo.model.Readrecord;
import com.example.demo.model.ReadrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReadrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    long countByExample(ReadrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int deleteByExample(ReadrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int insert(Readrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int insertSelective(Readrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    List<Readrecord> selectByExample(ReadrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    Readrecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Readrecord record, @Param("example") ReadrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int updateByExample(@Param("record") Readrecord record, @Param("example") ReadrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int updateByPrimaryKeySelective(Readrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrecord
     *
     * @mbg.generated Mon Aug 27 22:48:11 CST 2018
     */
    int updateByPrimaryKey(Readrecord record);
}